/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_avit_ads_pushads_ocg_GenerateFileJni */

#ifndef _Included_com_avit_ads_pushads_ocg_GenerateFileJni
#define _Included_com_avit_ads_pushads_ocg_GenerateFileJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_avit_ads_pushads_ocg_GenerateFileJni
 * Method:    geneTSFile
 * Signature: (Ljava/lang/String;IILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_avit_ads_pushads_ocg_GenerateFileJni_geneTSFile
  (JNIEnv *, jobject, jstring, jint, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
