alter table `t_productinfo` add COLUMN networkID varchar(20);
CREATE TABLE `t_productinfo_temp` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT '产品编码',
  `PRODUCT_NAME` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT '产品名称',
  `PRODUCT_DESC` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT '产品描述',
  `PRICE` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT '价格',
  `BILLING_MODEL_NAME` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'BillingModelName',
  `BILLING_MODEL_ID` VARCHAR(100) COLLATE utf8_general_ci DEFAULT NULL,
  `BILLING_MODEL_TYPE` VARCHAR(100) COLLATE utf8_general_ci DEFAULT NULL,
  `SP_ID` VARCHAR(100) COLLATE utf8_general_ci DEFAULT NULL,
  `IS_PACKAGE` CHAR(1) COLLATE utf8_general_ci DEFAULT NULL COMMENT '是否为产品包（0：产品、1：产品包）',
  `POSTER_URL` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT '产品海报地址',
  `TYPE` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL COMMENT '类型  回看产品类型标识是什么',
  `BIZ_ID` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT '计费代码',
  `BIZ_DESC` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT '计费描述',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '产品创建时间（yyyy-mm-dd hh:mm:ss）',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '产品修改时间（yyyy-mm-dd hh:mm:ss）',
  `STATE` CHAR(1) COLLATE utf8_general_ci DEFAULT NULL COMMENT '状态',
  `networkID` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL COMMENT '网络ID，县区局点对应的networkId',
  PRIMARY KEY (`ID`)
)ENGINE=InnoDB
AUTO_INCREMENT=716 CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT='产品信息临时表';

CREATE TABLE `t_channelinfo_npvr` (
  `CHANNEL_ID` VARCHAR(20) COLLATE utf8_general_ci NOT NULL DEFAULT '0' COMMENT '频道ID',
  `CHANNEL_CODE` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL COMMENT '频道 编码',
  `CHANNEL_TYPE` VARCHAR(200) COLLATE utf8_general_ci DEFAULT NULL COMMENT '频道类型',
  `CHANNEL_NAME` VARCHAR(20) COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '名称',
  `SERVICE_ID` VARCHAR(20) COLLATE utf8_general_ci DEFAULT '' COMMENT 'SERVICE_ID',
  `CHANNEL_LANGUAGE` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL COMMENT '语言',
  `CHANNEL_LOGO` VARCHAR(200) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Logo',
  `KEYWORD` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT '关键字',
  `LOCATION_CODE` VARCHAR(256) COLLATE utf8_general_ci DEFAULT NULL COMMENT '区域编码',
  `LOCATION_NAME` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL COMMENT '区域名称',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改时间',
  `STATE` CHAR(1) COLLATE utf8_general_ci DEFAULT NULL COMMENT '状态',
  `TS_ID` DECIMAL(10,0) DEFAULT NULL,
  `NETWORK_ID` DECIMAL(10,0) DEFAULT NULL,
  `CHANNEL_DESC` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT '描述',
  `IS_PLAYBACK` DECIMAL(1,0) DEFAULT '0' COMMENT '是否回放频道 1：是 0：否',
  `SUMMARYSHORT` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT '简称',
  `ID` INTEGER(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
)ENGINE=InnoDB
AUTO_INCREMENT=44 CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT='频道信息表; '

CREATE TABLE `t_channelinfo_npvr_temp` (
  `CHANNEL_ID` VARCHAR(20) COLLATE utf8_general_ci NOT NULL DEFAULT '0' COMMENT '频道ID',
  `CHANNEL_CODE` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL COMMENT '频道 编码',
  `CHANNEL_TYPE` VARCHAR(200) COLLATE utf8_general_ci DEFAULT NULL COMMENT '频道类型',
  `CHANNEL_NAME` VARCHAR(20) COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '名称',
  `SERVICE_ID` VARCHAR(20) COLLATE utf8_general_ci DEFAULT '' COMMENT 'SERVICE_ID',
  `CHANNEL_LANGUAGE` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL COMMENT '语言',
  `CHANNEL_LOGO` VARCHAR(200) COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Logo',
  `KEYWORD` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT '关键字',
  `LOCATION_CODE` VARCHAR(256) COLLATE utf8_general_ci DEFAULT NULL COMMENT '区域编码',
  `LOCATION_NAME` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL COMMENT '区域名称',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `MODIFY_TIME` DATETIME DEFAULT NULL COMMENT '修改时间',
  `STATE` CHAR(1) COLLATE utf8_general_ci DEFAULT NULL COMMENT '状态',
  `TS_ID` DECIMAL(10,0) DEFAULT NULL,
  `NETWORK_ID` DECIMAL(10,0) DEFAULT NULL,
  `CHANNEL_DESC` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT '描述',
  `IS_PLAYBACK` DECIMAL(1,0) DEFAULT '0' COMMENT '是否回放频道 1：是 0：否',
  `SUMMARYSHORT` VARCHAR(254) COLLATE utf8_general_ci DEFAULT NULL COMMENT '简称',
  `ID` INTEGER(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
)ENGINE=InnoDB
AUTO_INCREMENT=44 CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT='频道信息临时表; ';
--用户级别
CREATE TABLE `t_user_rank` (
  `USER_RANK_CODE` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL COMMENT '用户级别编码',
  `USER_RANK_NAME` VARCHAR(50) COLLATE utf8_general_ci DEFAULT NULL COMMENT '用户级别名称',
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `DESCRIPTION` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT '描述',
  `areacode` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
)ENGINE=InnoDB
AUTO_INCREMENT=6 CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT='用户级别信息表';
--用户级别临时表
CREATE TABLE `t_user_rank_temp` (
  `USER_RANK_CODE` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL COMMENT '用户级别编码',
  `USER_RANK_NAME` VARCHAR(50) COLLATE utf8_general_ci DEFAULT NULL COMMENT '用户级别名称',
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `DESCRIPTION` VARCHAR(255) COLLATE utf8_general_ci DEFAULT NULL COMMENT '描述',
  `areacode` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
)ENGINE=InnoDB
AUTO_INCREMENT=6 CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT='用户级别信息临时表';

--用户行业类别
CREATE TABLE `t_user_industry_category` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_INDUSTRY_CATEGORY_CODE` VARCHAR(5) COLLATE utf8_general_ci DEFAULT NULL COMMENT '行业编码',
  `USER_INDUSTRY_CATEGORY_VALUE` VARCHAR(50) COLLATE utf8_general_ci DEFAULT NULL COMMENT '行业名称',
  `areacode` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
)ENGINE=InnoDB
AUTO_INCREMENT=18 CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT='用户行业';

--用户行业类别临时表
CREATE TABLE `t_user_industry_category_temp` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_INDUSTRY_CATEGORY_CODE` VARCHAR(5) COLLATE utf8_general_ci DEFAULT NULL COMMENT '行业编码',
  `USER_INDUSTRY_CATEGORY_VALUE` VARCHAR(50) COLLATE utf8_general_ci DEFAULT NULL COMMENT '行业名称',
  `areacode` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
)ENGINE=InnoDB
AUTO_INCREMENT=18 CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT='用户行业临时表';

--双向区域信息表
CREATE TABLE `t_location_code` (
  `LOCATIONCODE` DECIMAL(12,0) DEFAULT NULL COMMENT '150000000000',
  `LOCATIONNAME` VARCHAR(200) COLLATE utf8_general_ci DEFAULT NULL,
  `PARENTLOCATION` DECIMAL(12,0) DEFAULT NULL,
  `LOCATIONTYPE` VARCHAR(2) COLLATE utf8_general_ci DEFAULT NULL,
  `areacode` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL,
  KEY `location_code_index` (`LOCATIONCODE`, `areacode`)
)ENGINE=InnoDB
CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT='区域信息表';

--双向区域信息临时表
CREATE TABLE `t_location_code_temp` (
  `LOCATIONCODE` DECIMAL(12,0) DEFAULT NULL COMMENT '150000000000',
  `LOCATIONNAME` VARCHAR(200) COLLATE utf8_general_ci DEFAULT NULL,
  `PARENTLOCATION` DECIMAL(12,0) DEFAULT NULL,
  `LOCATIONTYPE` VARCHAR(2) COLLATE utf8_general_ci DEFAULT NULL,
  `areacode` VARCHAR(20) COLLATE utf8_general_ci DEFAULT NULL
 )ENGINE=InnoDB
CHARACTER SET 'utf8' COLLATE 'utf8_general_ci'
COMMENT='区域信息临时表';



